### ISSUE TITLE
Is possible to use sms authentication with the API?

### ISSUE THREAD

**Issue by dMiracleMan** [signnow/SignNow.NET#100]
Always get an error saying that only password or phone authentication is available. What should be the phone number format when sending it to the api?

**Comment by AlexNDRmac** [comment]
Yes, you can set authentication by SMS. Please use `SignerOptions` built-in method: `SetAuthenticationBySms()` 
Example:
```csharp
var content = new SignerOptions("test@email.com", role)
{
    RemindAfterDays = 1
}
.SetAuthenticationBySms("800 831-2050");
```
Phone number format should be a valid US phone number including area code e.g., (123) 456-7890
