### ISSUE TITLE
Able to get Token but, nothing else

### ISSUE THREAD

**Issue by wtlease** [signnow/SignNow.NET#101]
Any ideas why I am able to get a Token AND verify it as true but, whenever I try to do anything else (upload document, download document, get current user, etc.).  I get a response that has "Invalid Token" "code 1537".

Spent about 8 hours trying different things and can't figure out what I may be doing wrong.

Thank you.

**Comment by AlexNDRmac** [comment]
I suppose you have missed smth in you credentilals. Please try something from solution with Examples or provide some code sample to reproduce your issue.

**Comment by wtlease** [comment]
Did those credentials work for you then?  Or, did they not work for you?

 

I can’t get your code to work or the examples… those are the credentials I am using. 

 

clientId = "7f654fea3b296431e2fa014918b428d7"

clientSecret = "cb9c73b847f2ad1a961a3ee2f60f49f3"

userLogin = "terry.lease@boatclubsoftware.com"

userPassword = "123.BoatClub"

**Comment by wtlease** [comment]
I suppose you have missed smth in you credentilals. Please try something from solution with Examples or provide some code sample to reproduce your issue.

**Comment by wtlease** [comment]
Hi Alexander.  This is the code I am using.  

 

I am able to get a valid token but, no matter what function I try after that I get the “invalid token” error.

 

Public Shared Async Function UploadDoc(S As String) As Task(Of Boolean)

 

        Dim apiBaseUrl = New Uri("https://api-eval.signnow.com")

        Dim clientId = "****************************"

        Dim clientSecret = "****************************"

        Dim userLogin = "**************************"

        Dim userPassword = "****************"

 

 

 

        Dim oauth = New OAuth2Service(apiBaseUrl, clientId, clientSecret)

        Dim O = Await oauth.GetTokenAsync(userLogin, userPassword, Scope.All).ConfigureAwait(False)

        Dim document

        Dim signNowContext = New SignNowContext(O)

        Using fileStream = File.OpenRead(S)

            Try

                document = Await signNowContext.Documents.UploadDocumentAsync(fileStream, "Foo.pdf")

                Console.WriteLine(document.Id)

                Return True

            Catch ex As Exception

 

            End Try

 

        End Using

 

        Return False

    End Function

**Comment by wtlease** [comment]
Solved!

 

var signNowContext = new SignNowContext(baseUri, token);

 

BaseURI was missing in my call.

 

Thank you.
