### ISSUE TITLE
Make "from" a Settable Property

### ISSUE THREAD

**Issue by ghost** [signnow/SignNow.NET#102]
Currently invites have a hardcoded sender - see here [UserService.cs](https://github.com/signnow/SignNow.NET/blob/fef5d2eef7b498d82797d4545217bb43ea97fcda/SignNow.Net/Service/UserService.cs#L48)

The API allows setting "from" for the invites. Please make this field settable in the .NET SDK.

Thanks!

**Comment by AlexNDRmac** [comment]
It's not a hardcoded sender. Sender always must be a document owner. You can not create invite to sign the document if you are not own this document.
If you'll look at line 46 in [UserService.cs](https://github.com/signnow/SignNow.NET/blob/fef5d2eef7b498d82797d4545217bb43ea97fcda/SignNow.Net/Service/UserService.cs#L46) - you'll see that `sender` - it's always document owner (we retrieve it using token)

If you want to personalize an invitation email, you can use [Subject/Message](https://github.com/signnow/SignNow.NET/blob/fef5d2eef7b498d82797d4545217bb43ea97fcda/SignNow.Net/Model/SignInvite.cs#L20) for customization.

**Comment by ghost** [comment]
@AlexNDRmac thank you for the quick response! I assumed that the sender is assignable because the API has it in the request body schema - https://docs.signnow.com/reference/oas/document/postdocumentdocumentidinvite
