### ISSUE TITLE
Download json or csv data list of signed documents

### ISSUE THREAD

**Issue by WilliamsKobie** [signnow/SignNow.NET#103]
I can't find it in the docs of this sdk, but is there a way to download a list of signed document data using json or csv.

**Comment by AlexNDRmac** [comment]
`SignNowDocument` model have the document metadata, you can iterate over it to get properties.
You can download signed document when the signing process was completed.
In future versions we'll implement document groups, so you'll able work with multiple documents.

**Comment by WilliamsKobie** [comment]
I'll give it a try thanks.

**Comment by AlexNDRmac** [comment]
Maybe you can describe your use case in details... I'll try to propose best suitable solution for your case.
