### ISSUE TITLE
"String was not recognized as a valid DateTime." on GetDocument 

### ISSUE THREAD

**Issue by hasan9444** [signnow/SignNow.NET#104]
when I place a radio button on document and try to get Document using your packages.
It got crash with the following error

"String was not recognized as a valid DateTime."

Able to fetch using simple API but not using
`var document = await signNowContext.Documents.GetDocumentAsync(documentId).ConfigureAwait(true);`

**Comment by AlexNDRmac** [comment]
Thank you for your response, I'll try to check it ASAP.

**Comment by AlexNDRmac** [comment]
@hasan9444 it will be fixed soon, thank you for report.
