### ISSUE TITLE
Add "CC" string array property to SignInvite

### ISSUE THREAD

**Issue by schroe2a** [signnow/SignNow.NET#106]
Hi Guys,
My client is asking to include a CC on an invite. I'm hoping this is a fairly straightforward addition to the class along with the JsonProperty attribute.

If you know for sure it will be some time before this can be added that information would be useful as I'll need to fallback to a manual HttpClient request approach.

Thanks!

**Comment by AlexNDRmac** [comment]
Thanks for you feedback, I’ll add CC feature in next version.

**Comment by AlexNDRmac** [comment]
Already in v0.6.0-beta. Thank you.
