### ISSUE TITLE
is this a WiP? It Doesn't support many endpoints

### ISSUE THREAD

**Issue by nkigen** [signnow/SignNow.NET#107]
Hi,
Does this package plan to support all the SignNow API endpoints in future? Looks like its currently supporting on the basic ones. If not do you accept pull requests to improve on this package?

**Comment by AlexNDRmac** [comment]
Hu @nkigen. This package will support all the SignNow features in future.

**Comment by IvanBil** [comment]
@nkigen Yes, we accept pull requests. Also pay attention that currently, the library is in beta and doesn't support all the features of SignNow web API. Additionally, you are free to make feature requests here.
