### ISSUE TITLE
We are getting an error message when we call the GetTokenAsync()

### ISSUE THREAD

**Issue by pachumon** [signnow/SignNow.NET#115]
We are getting an error message stating that the below message System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. this occurs when we call the GetTokenAsync method and we have all the right set of credential details . help would be much appreciated

**Comment by AlexNDRmac** [comment]
Could you please try to run Authorisation Example from `SignNow.NET.Examples` solution.
Uncomment lines and replace in [example](https://github.com/signnow/SignNow.NET/blob/6d3d9530dae2e3c33e6f82be89098324b8345c05/SignNow.Net.Examples/ExamplesRunner.cs#L66) credentials with your own, then try to run [RequestAccessTokenTest()](https://github.com/signnow/SignNow.NET/blob/6d3d9530dae2e3c33e6f82be89098324b8345c05/SignNow.Net.Examples/ExamplesRunner.cs#L104)

**Comment by AlexNDRmac** [comment]
@pachumon - any update?
