### ISSUE TITLE
How do you move a document into the archive folder?

### ISSUE THREAD

**Issue by patrickb84** [signnow/SignNow.NET#121]
I can't find any documentation for moving documents to the archive folder, am I missing something?

EDIT: I also can't find any code in .NET to create folders/move documents to folders, just the CURL commands. Do those exist?

**Comment by AlexNDRmac** [comment]
Hi @ patrickb84, in the current version of the SDK, folders and operations with them are not yet implemented. We plan to implement this in the next version.

**Comment by AlexNDRmac** [comment]
@patrickb84 next version is coming soon... you can see example with how to move the documents to the specified folder: https://github.com/signnow/SignNow.NET/blob/develop/SignNow.Net.Examples/Documents/MoveTheDocumentToFolder.cs

**Comment by AlexNDRmac** [comment]
@patrickb84 You can move documents to specified folder with SDK v0.9.0, pls check examples for details.
