### ISSUE TITLE
Create document from the template

### ISSUE THREAD

**Issue by halfdead2296** [signnow/SignNow.NET#127]
When I use create document from template I get followiing error
![Untitled](https://user-images.githubusercontent.com/87530685/125949085-0a59a661-fc14-49a3-8108-d50739f69383.jpg)

**### Following is my code**
    public static async Task<CreateDocumentFromTemplateResponse> CreateDocumentFromTheTemplate(string documentName, string templateId, Token token)
        {
            // using token from the Authorization step
            var signNowContext = new SignNowContext(token);

            return await signNowContext.Documents
                .CreateDocumentFromTemplateAsync(documentName, templateId)
                .ConfigureAwait(false);
        }

**and I generated token using** 
public static async Task<Token> RequestAccessToken(Uri apiBase, CredentialModel clientInfo)
        {
            Uri apiBaseUrl =new Uri("https://api-eval.signnow.com");

            string clientId = clientInfo.ClientId;
            string clientSecret = clientInfo.ClientSecret;

            string userLogin = clientInfo.Login;
            string userPassword = clientInfo.Password;

            var oauth = new OAuth2Service(apiBaseUrl, clientId, clientSecret);

            return await oauth.GetTokenAsync(userLogin, userPassword, Scope.All)
                .ConfigureAwait(false);
        }

**Comment by AlexNDRmac** [comment]
It looks that smth wrong with your credentials. Please double check your clientId, clientSecret and Login/Password.

**Comment by halfdead2296** [comment]
I validated Token using following , and it returns true
   
   
    /// <summary>
        /// Verify access token example
        /// </summary>
        /// <param name="apiBaseUrl">SignNow API base URL. Sandbox: "https://api-eval.signnow.com", Production: "https://api.signnow.com"</param>
        /// <param name="clientInfo"><see cref="CredentialModel"/> with Application Client ID and Client Secret</param>
        /// <param name="token">Access token</param>
        /// <returns></returns>
        public static async Task<bool> VerifyAccessToken(Uri apiBaseUrl, CredentialModel clientInfo, Token token)
        {
            var oauth2 = new OAuth2Service(apiBaseUrl, clientInfo.Login, clientInfo.Password);

            return await oauth2.ValidateTokenAsync(token)
                .ConfigureAwait(false);
        }

**Comment by halfdead2296** [comment]
and to note on ds 
 .CreateDocumentFromTemplateAsync(documentName, templateId)
            .ConfigureAwait(false);
            
            here in your document order of prameter mismatches with the CreateDocumentFromTemplateAsync function defination

**Comment by AlexNDRmac** [comment]
> and to note on ds
> .CreateDocumentFromTemplateAsync(documentName, templateId)
> .ConfigureAwait(false);
> 
> ```
>         here in your document order of prameter mismatches with the CreateDocumentFromTemplateAsync function defination
> ```

Thanks, I''l fix it in next version

Did you try to use `SingnNow.Net.Examples` solution? Using these examples - all should works.

**Comment by halfdead2296** [comment]
Yes thankyou for the fix, closing the issue
