### ISSUE TITLE
error invalid_token

### ISSUE THREAD

**Issue by NechamaMiller** [signnow/SignNow.NET#128]
I am trying to call GetDocumentAsync using the following code:

        `Dim docId = "a561139515f0486ea3643fc7051ab8b6393c091f"
        Dim accessToken = xxx
        Dim tkn = New Token With {
                           .AccessToken = accessToken
                           }

        Dim ctx As New SignNowContext(tkn)

        Dim svc = New OAuth2Service(clientKey, secretKey)

        Dim valid As Boolean = svc.ValidateTokenAsync(tkn).GetAwaiter().GetResult()

        Console.WriteLine("Valid? " & valid)

        Try
            Dim doc As SignNowDocument = ctx.Documents.GetDocumentAsync(docId).GetAwaiter().GetResult()
        Catch ex As Exception
            Console.WriteLine(ex)
        End Try`

This is the output that I get:

> Valid? True
> SignNow.Net.Exceptions.SignNowException: invalid_token
>    at SignNow.Net.Internal.Service.SignNowClient.<ProcessErrorResponse>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SignNow.Net.Internal.Service.SignNowClient.<RequestAsync>d__12`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SignNow.Net.Internal.Service.SignNowClient.<RequestAsync>d__10`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at SignNow.Net.Service.DocumentService.<GetDocumentAsync>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at EsignNewApiTest.Module1.Test() in C:\Users\pc\source\repos\EsignNewApiTest\EsignNewApiTest\Module1.vb:line 29

As you can see, the token is validating properly, but I still get an error invalid_token when I try to get the document. I reached out to your support team by email but they were not able to help me. Can you tell me why this does not work and what I can do to make this work? 

I cannot get the token using username and password because I am submitting this for a 3rd party. They log in on the front end, I save the token in the database, and then I need to use it in a back-end process to send to SignNow

**Comment by AlexNDRmac** [comment]
Hi @NechamaMiller. In your example you are making one simple mistake - manually creating the Token object. In this case, you have `invalid_token` because you are not setting a token type property. To avoid this situation, you should use the following:

```vb
Dim tkn = New Token With {
                       .AccessToken = accessToken,
                       .TokenType = TokenType.Bearer
                       }
```

**Comment by NechamaMiller** [comment]
Thank you! That worked
