### ISSUE TITLE
FieldContent Examples

### ISSUE THREAD

**Issue by roberto-co** [signnow/SignNow.NET#130]
Hello, could you provide a way to use the FieldContents when uploading a document please. I can't seem to get it uploaded with FieldContents such as the AttachmentContent.

**Comment by AlexNDRmac** [comment]
Hello @roberto-co, sorry for the late answer.
Current version of SDK does not support settingFieldContent when uploading the documents. This feature is not implemented on Service for the Documents. We plan to add support for FiledContent and other properties in next SDK version.
Of course, you can implement this yourself if you can't wait, using API documentation and SDK sources.

**Comment by roberto-co** [comment]
Thanks Alex I was able to add the functionality to the library.
