### ISSUE TITLE
Webhook implementation

### ISSUE THREAD

**Issue by FedericoBernardi** [signnow/SignNow.NET#136]
Is there any way to use webhooks with this library? 
I managed to fit all our integration with this library! Great job! Only the webhooks are missing

**Comment by AlexNDRmac** [comment]
Currently webhooks are not implemented, but this feature can be implemented in next version.
If you can wait, I'll implement webhooks with some other feature in next SDK version. ETA ~2 weeks.

**Comment by FedericoBernardi** [comment]
> Currently webhooks are not implemented, but this feature can be implemented in next version. If you can wait, I'll implement webhooks with some other feature in next SDK version. ETA ~2 weeks.

Thanks for the reply, of course I can wait. I'll test as soon as it will be available :-)
FYI, one more missing feature I think is template upload. A workaround I've found is creating a document, transform the document into template and delete the document

Thanks again

**Comment by FedericoBernardi** [comment]
Hi Alex, any update about webhooks?

**Comment by AlexNDRmac** [comment]
Sorry, but Russia attacked my country... we have a war. I'll try to implement as soon as I can

**Comment by FedericoBernardi** [comment]
No problem, really, I understand. The situation in Ukraine is orribile. The whole democratic world is on your side

**Comment by nmg196** [comment]
Hope you're OK Alex!  This situation is absolutely terrible.

**Comment by AlexNDRmac** [comment]
Thank you for you support! I'm fine as it can be possible in this situation and trying to implement webhooks.

**Comment by nmg196** [comment]
Great to hear. I'm amazed how great support has continued to be on Live Chat with all your country is going through.
In the mean time I think I can still make use of webhooks using the bare RestAPI and restsharp.

**Comment by AlexNDRmac** [comment]
I'm working on webhooks implementation now. With your own implementation you might miss some edge cases like data validation, response/request conversion. So if you can wait, I'll try to speedup with implementation.

**Comment by nmg196** [comment]
Yeah don't rush it :)  For me it appears to be working OK in Postman.   The only thing I'm not sure about is the possible values for "event" as the docs don't really say. But that said - I have a feeling all I need is "document.complete"

**Comment by nmg196** [comment]
Do you know if there is a way to subscribe to all "document.complete" events in a particular account? Otherwise I think I need to set up a new webhook for each document (entity_id) individually?

**Comment by AlexNDRmac** [comment]
`user.document.complete` should help with subscription for all the documents.

**Comment by nmg196** [comment]
Regarding the Webhooks 2.0 API, this really caught me out: 

- The API endpoint for create or delete (verbs: POST / DELETE) webhooks (events) uses a **Bearer token.** 
- The API endpoint for getting webhooks (verb GET) uses **Basic Auth!**
- The API endpoint for updating (PUT) uses **Bearer token**  **OR** **Basic Auth**

Really confusing. I don't know why all 4 don't just use Basic Auth for all 4 verbs.

Thanks
Nick

**Comment by alexmohr1966** [comment]
Hi, any update on webhook integration? I am currently evaluating the signNow API and webhooks would be such a useful feature. 
Thanks,
Alex

**Comment by AlexNDRmac** [comment]
Need to finish with GET events implementation, other methods are implemented. I'll back to work on it soon, sorry for the long delay.

**Comment by alexmohr1966** [comment]
Thanks Alex for your reply. Any chance for sharing the code for creating an event subscription?

**Comment by nmg196** [comment]
If you need a stop gap (as I did)  it's pretty easy to do by hand with a lib like RestSharp (etc).  I made a few methods like this to fill in the gaps where there was no C# API.  I didn't want ot put Alex under more stress with what he's already dealing with in Ukraine ❤️ 

![image](https://user-images.githubusercontent.com/8134047/218494446-71f76b4c-e40e-4cae-bd84-b36b0cd1817a.png)

**Comment by alexmohr1966** [comment]
Thank you @nmg196, much appreciated.

**Comment by AlexNDRmac** [comment]
implemented in v1.3.0, please update signNow packages and use. Thanks
