### ISSUE TITLE
Prefilled Text

### ISSUE THREAD

**Issue by FedericoBernardi** [signnow/SignNow.NET#137]
According to the signNow api prefilled text should accept  "field_name" and "prefilled_text" but in the implementation it has "prefilled_text" and "label".
Am I missing something or TextField should serialise "field_name" instead "label"?

reference: https://docs.signnow.com/sn/ref/document/#prefilled-text

**Comment by AlexNDRmac** [comment]
Hi @FedericoBernardi, sorry for the late response. SDK has internal requests model with proper serialisers.
We provide a simple and uniform property name, you don't have to worry about the structure of API requests, because we automatically convert all the required properties inside the SDK.
