### ISSUE TITLE
How can you get a non expiring API key?

### ISSUE THREAD

**Issue by nmg196** [signnow/SignNow.NET#138]
I'm confused how the authentication for SignNow API works. Why does it seem to need a human's username and password?  If I embed those in my web application and then change my password, the app will break.

What is the intended workflow so that you can use the API indefinitely without human intervention?  I was expecting it to use just a Bearer token or API key but it seems this can only be used to request a token from a real person's account.

I don't think you can use Basic auth to actually upload documents (etc)?

Thanks!
Nick

**Comment by AlexNDRmac** [comment]
Please take a look authentication via `authorization_code` grant type ([documentation](https://docs.signnow.com/docs/signnow/ZG9jOjM3OTI3NTY2-features#authentication))

**Comment by nmg196** [comment]
Thanks for your quick reply. I will take a look.

I sincerely hope you, your family and colleagues are safe given what is happening in Ukraine. You have my best wishes! We are on your side.

**Comment by AlexNDRmac** [comment]
Thank you for your support in this difficult time for the Ukrainian nation.

**Comment by nmg196** [comment]
How long is authorization_code valid for? Does it expire?

**Comment by nmg196** [comment]
OK I've got this working now - thanks so much! 

We hope you and your team are all OK if they are still in Ukraine.
