### ISSUE TITLE
One time download link does not work with .NET HttpClient

### ISSUE THREAD

**Issue by chashik** [signnow/SignNow.NET#140]
I've encountered a problem with local API client.
I've obtained one time download link with the SignNow.NET API client as described here:
https://docs.signnow.com/docs/signnow/b3A6NDAwNjQwNTY-get-document-download-link
Download link works fine via web-browser. But if I try to download via .NET HttpClient the request fails with 400 Http status code:
![image](https://user-images.githubusercontent.com/45169858/162069962-e2b4eb37-f9fb-4185-af68-2e850642355d.png)
Do I miss headers or anything else?
Yet DownloadDocumentResponse alternative is not very convenient for integration with our current project.
Thanks in advance.

**Comment by AlexNDRmac** [comment]
Hi @chashik. You missed redirect. One time download link - its not a direct download link. You should handle Response with 3xx code and read `location` from response headers. Use this link from `location` to read the file content.

**Comment by chashik** [comment]
> Hi @chashik. You missed redirect. One time download link - its not a direct download link. You should handle Response with 3xx code and read `location` from response headers. Use this link from `location` to read the file content.

Thank you, missed redirect and response analysis at all. Switched to Stream download but will finish up on that one too.
