### ISSUE TITLE
RefreshAccessToken method

### ISSUE THREAD

**Issue by TommyGunz2935** [signnow/SignNow.NET#141]
Hi,

I am able to RequestAccessToken, then VerifiyAccessToken but when I try to RefreshAccessToken I get invalid_client. When I take the same access token and try to refresh it through Postman it works. I am not sure if I am doing something wrong but I thought that to refresh access token I supposed to use the refresh token instead of  .login and .password, which would be different from this method below? 

Am I missing something? 

Any help would be appreciated 
Thank you 
Tom

public static async Task<Token> RefreshAccessToken(Uri apiBaseUrl, CredentialModel clientInfo, Token token)
        {
            var oauth2 = new OAuth2Service(apiBaseUrl, clientInfo.Login, clientInfo.Password);

            return await oauth2.RefreshTokenAsync(token)
                .ConfigureAwait(false);
        }

**Comment by AlexNDRmac** [comment]
Please check [AcceptanceTest](https://github.com/signnow/SignNow.NET/blob/08fd325d086d71c35b0f1919da2f5e89585033e8/SignNow.Net.Test/AcceptanceTests/OAuth2ServiceTest.cs#L109) for refresh token method.

This example might helps you to sort out with RefreshToken obtaining.
```csharp
_apiCredentials = new CredentialModel
{
    Login = "user_eamail@noemail.com",
    Password = "your-secret-password",
    ClientId = "your-application-client-id",
    ClientSecret = "your-application-client-secret"
};

oauth = new OAuth2Service(_apiCredentials.ClientId, _apiCredentials.ClientSecret);

var token = await oauth
                .GetTokenAsync(_apiCredentials.Login, _apiCredentials.Password, Scope.All)
                .ConfigureAwait(false);
var freshToken = await oAuthTest.RefreshTokenAsync(token).ConfigureAwait(false);
```

**Comment by TommyGunz2935** [comment]
Hi Alex,

Thank you for pointing it out. I'll be playing with this code upcoming week. 

Tom
