### ISSUE TITLE
Credential Model is not found in .net 4.6.1 winforms

### ISSUE THREAD

**Issue by Lynx5502** [signnow/SignNow.NET#143]
Hello,
Trying to implement this but I cannot get over the credential model error.
Enclosed is a screen shot.

http://prntscr.com/BEPAyydzj0IJ

**Comment by AlexNDRmac** [comment]
Hi. It's not necessary to use Credential.Model in your code. This model using in signNow tests as simple object with properties.
You can find this model here: https://github.com/signnow/SignNow.NET/blob/develop/SignNow.Net.Test/Context/CredentialModel.cs
