### ISSUE TITLE
Unable to use  signNowContext.Documents.EditDocumentAsync

### ISSUE THREAD

**Issue by cryystyy** [signnow/SignNow.NET#145]
I am getting the following error:
Unable to cast object of type 'System.Collections.Generic.List`1[Infrastructure.Models.SigningDocuments.SignNowFieldDto]' to type 'System.Collections.Generic.List`1[SignNow.Net.Interfaces.IFieldEditable]'.

However my class SignNowFieldDto is implementing IFieldEditable.

![image](https://user-images.githubusercontent.com/6780182/206915550-ee191df1-cc11-46fc-ba1d-0c9c34cbd6a3.png)

**Comment by AlexNDRmac** [comment]
Hi @cryystyy 
I cannot help without small reproducing part of code. It looks like you trying to re-use some parts of SDK without full implementation of specific classes and converters.
What is - `FieldType` in your code? How to make explicit cast from signNow FiledType object to your implementation?

**Comment by cryystyy** [comment]
It's a problem from my part, actually. after hours of debugging if i deserialize the list of objects i am sending do not properly conver to a list of IFieldEditable even though i cast it. I had to recreate the list in order to have the proper type.
