### ISSUE TITLE
User provided HttpClient support

### ISSUE THREAD

**Issue by TomGathercole** [signnow/SignNow.NET#148]
Looking through the SDK code, it appears that SignNowContext (and indeed anything that inherits WebClientBase) ends up instantiating an HttpClient each time that object is instantiated. This can lead to socket exhaustion and performance issues if used incorrectly (see [Issues with the original HttpClient class available in .NET](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net)).

Fortunately, it is fairly simple to support integration with HttpClientFactory (without breaking .Net4.5 compatability). There's a couple of ways that could happen in this project:
* Make `SignNowClient` public, and make the `OAuth2Service` and `SignNowContext` constructors accepting `SignNowClient` public
* Add constructors accepting `HttpClient` to  `OAuth2Service` and `SignNowContext`, and instantiate a `SignNowClient` within these classes.

Personally, I think the former would be the simplest approach and I would be happy to work on a PR to implement this. It might be worth noting that this also has other benefits aside from performance including the ability to use middleware like Polly as well as improved testability.

**Comment by AlexNDRmac** [comment]
Since first SDK version we decided to close internal http client configuration because we might have some internals things whith breaking changes. But now this limitation is not requires, so I'll change current implementation to support DI.
