### ISSUE TITLE
GetDocumentAsync fails for documents using stamp fields

### ISSUE THREAD

**Issue by TomGathercole** [signnow/SignNow.NET#149]
When a stamp field is added to a document, the `Documents.GetDocumentAsync(...)` method fails with error:
```
Error converting value "stamp" to type 'SignNow.Net.Model.FieldType'. Path 'fields[3].type', line 1, position 7342.
```

It looks like this might be because the [FieldType](https://github.com/signnow/SignNow.NET/blob/develop/SignNow.Net/Model/Field.cs#L75) enum does not include an entry for the `stamp` type.

**Comment by AlexNDRmac** [comment]
Thank you for reporting this. I'll add this field.
