### ISSUE TITLE
"Unexpected Character" error when using GetDocumentHistoryAsync

### ISSUE THREAD

**Issue by SimonEvans482** [signnow/SignNow.NET#152]
I received an unexpected character error when using the GetDocumentHistoryAsync method - being hit upon the deserialisation of the returned json.

Issue is with the "JsonAttributes" property in the DocumentHistoryResponse Class - it is defined as String, but I was receiving a Key/Value pair. I changed the type to "Dynamic" (locally) and the issue is resolved.

**Comment by AlexNDRmac** [comment]
Fixed in v1.2.3, thank you for report
