### ISSUE TITLE
Document Group

### ISSUE THREAD

**Issue by chacham2** [signnow/SignNow.NET#161]
We are looking to send multiple documents in one envelope. Has that been implemented?

**Comment by AlexNDRmac** [comment]
Hi @chacham2, yes, Document Group features can be implemented and published with next release.

**Comment by chacham2** [comment]
That would be amazing. Our current project is automating a (manual) system that uses document groups, and so that is a required feature, at least on our end. May i ask if there is a timeline for the next release?

**Comment by AlexNDRmac** [comment]
There is no timeline, but main functionality (Create, Copy, Delete, Get) with Document Group might be implemented till the end of October. Other features, like metainfo - later.

**Comment by AlexNDRmac** [comment]
implemented in v1.3.0
