### ISSUE TITLE
invalid_client in Asp MVC

### ISSUE THREAD

**Issue by Ammar441** [signnow/SignNow.NET#81]
Line 22:             var oauth = new OAuth2Service(clientId, clientSecret); 
Line 23:  Line 24:             var token = oauth.GetTokenAsync(userLogin, userPassword,Scope.All).Result;
--

**Comment by AlexNDRmac** [comment]
Hi @Ammar441, could you please give more details.. or steps to reproduce. Also you can see OAuth2 service tests in SignNow.Net.Tests and compare it with you code.

**Comment by Ammar441** [comment]
please give me link example for asp mvc

**Comment by AlexNDRmac** [comment]
We don't have any samples for ASP.NET MVC. If you have any trouble with authorization, pls describe it more detailed, so we could help you with solution. Or contact with ours support https://support.signnow.com

**Comment by Ammar441** [comment]
i insert clientid and clientSecret also userlogin and password and Pass the variables
like this
 string clientId = "my clientid";
string clientSecret = "clientSecret";

            string userLogin = "my email";
            string userPassword = "my password";
var oauth = new OAuth2Service(clientId, clientSecret);

var token = oauth.GetTokenAsync(userLogin, userPassword,Scope.All).Result;

**Comment by AlexNDRmac** [comment]
Lets clarify your example:

```csharp
// I'm using signnow Sandbox api url:
var ApiBaseUrl = new Uri("https://api-eval.signnow.com");

// App credentials from signnow account
var clientId = "your-clientId-from-siggnow-account";
var clientSecret = "your-client-secret-from-signnow-account";

// User credentials
var login = "your-user-email@noemail.com";
var password = "your-secret-password";

// init OAuth2 service
var oauth2 = new OAuth2Service(ApiBaseUrl, clientId, clientSecret);
// Token retrieval
var token = oauth2.GetTokenAsync(login, password, Scope.All).Result;
```

With the correct credentials, there should be no errors. Pls check.

**Comment by Ammar441** [comment]
great is work But I had another problem read pdf doucment **invalid_Token**
var pdfFilePath = Server.MapPath("~/document/test.pdf");
            var pdfFileName = "test.pdf";
           
            // using token from the Authorization step
            var signNowContext = new SignNowContext(token);

            using (var fileStream =  System.IO.File.OpenRead(pdfFilePath))
            {
            var uploadResponse = signNowContext.Documents.UploadDocumentAsync(fileStream, pdfFileName).Result;

            documentId = uploadResponse.Id;
            }

**Comment by Ammar441** [comment]
I want to make a signature on pdf files through my site, and after the signature is completed, the file will be modified and replaced with the signed file

**Comment by AlexNDRmac** [comment]
All SignNow services works with authorization. You should check for valid Token. OAuth service has method for token validation. Also... more comfortable is using SignNow context class, because it like service container and you can easily get any of signnow services without care about authorization for each service

**Comment by IvanBil** [comment]
@Ammar441 Could you clarify what version of the SignNow.NET do you use, please? Also, please provide us the complete code sample or project so that we could test on our side.

**Comment by AlexNDRmac** [comment]
@Ammar441 if you have any questions, please reopen issue.
