### ISSUE TITLE
Error getting token

### ISSUE THREAD

**Issue by dMiracleMan** [signnow/SignNow.NET#89]
I'm getting error when trying to connect to the demo api.

Here is my code

  string clientId = ConfigurationManager.AppSettings["SignNowClientId"].ToString();
            string clientSecret = ConfigurationManager.AppSettings["SignNowClientSecret"].ToString();
            string SignNowUser = ConfigurationManager.AppSettings["SignNowUser"].ToString();
            string SignNowPass = ConfigurationManager.AppSettings["SignNowPass"].ToString();
            string SignNowApiPath = ConfigurationManager.AppSettings["SignNowAPIPath"].ToString();

            Uri apiPath = new Uri(SignNowApiPath);
            // init OAuth2 service
            var oauth = new OAuth2Service(apiPath, clientId, clientSecret);
            // Token retrieval
            var token = oauth.GetTokenAsync(SignNowUser, SignNowPass,Scope.User).Result;

![Capture](https://user-images.githubusercontent.com/2863183/78512747-f5aeb280-7774-11ea-979f-cd2e9055116d.PNG)

**Comment by AlexNDRmac** [comment]
Hi @dMiracleMan 
As I see on your screenshot, you are using Windows... What version of SignNow.Net SDK do you use and what version of .Net Framework?

**Comment by dMiracleMan** [comment]
.net framework 4.7.2
signnow.net 0.5.0-beta

**Comment by AlexNDRmac** [comment]
Pls check if you proper set values into your application configuration.
Also, check for proper sandbox Url: `https://api-eval.signnow.com`, because `Not found` error message more related to some issue with Url.

**Comment by dMiracleMan** [comment]
Here is what I have
<add key="SignNowAPIPath" value="https://app-eval.signnow.com" />

**Comment by dMiracleMan** [comment]
// Api URL (Sandbox or Production)
var apiBaseUrl = new Uri("https://api-eval.signnow.com");

**Comment by AlexNDRmac** [comment]
Please try to check if you can obtain token with your credentials using simple `Curl` from [API reference](https://docs.signnow.com/authentication#authentication)
Also, I need some small code sample from you to reproduce the same possible issue with token retrieval.

**Comment by dMiracleMan** [comment]
I had an error in the URL, but with the url fixed, now I get the following error:

![image](https://user-images.githubusercontent.com/2863183/78586149-03157c80-7809-11ea-994c-875c8a56d8a4.png)

**Comment by dMiracleMan** [comment]
I had an error in the client Id also.

**Comment by AlexNDRmac** [comment]
This is because smth wrong with your `SignNowPass` or/and clientId

**Comment by dMiracleMan** [comment]
working now. thank

**Comment by dMiracleMan** [comment]
Thanks
