### ISSUE TITLE
How do I create fields in a document programatically?

### ISSUE THREAD

**Issue by dMiracleMan** [signnow/SignNow.NET#90]
Can it be done with this library?

**Comment by AlexNDRmac** [comment]
Yes, but not with the current beta. This feature will be implemented in future versions.
In the current version, you can create Freeform / Field invites and get the values of all fields.

What feature are you trying to implement?

**Comment by AlexNDRmac** [comment]
@dMiracleMan also, you can upload document with field tags and you will have fields in the document.

**Comment by dMiracleMan** [comment]
I have an app that generates documents (contracts). I would like to upload those documents and send them for signature.  When I currently try to generate a signature link to send, the library would give me an error that I dont have any fields in the document.

**Comment by AlexNDRmac** [comment]
With current beta you can’t add signature field programmatically, it will be possible with new version.
For your use case, I can propose to add signature tag to your document, then upload document with field extract. And after those steps you’ll have signature field. To send the document for sign - just create Role-based invite.

We will add code samples with these cases ASAP, it should help you with steps for implementation.

**Comment by AlexNDRmac** [comment]
@dMiracleMan - there is [example with field extract](https://github.com/signnow/SignNow.NET/blob/develop/SignNow.Net.Examples/Documents/UploadDocumentWithFieldExtract.cs).

**Comment by dMiracleMan** [comment]
I've been trying to add a signature tag unsuccessfully to my documents.  Can you provide a signature sample? the string only.

**Comment by AlexNDRmac** [comment]
`{{t:t;r:n;o:"Signer 1";}}` - it's a signature tag. Place it into your document, than you will be able to extract this field.

**Comment by dMiracleMan** [comment]
Got it working. Signature looks really, really small once it is done.  Any workaround?

**Comment by AlexNDRmac** [comment]
Yes... you can specify field size: `{{t:s;r:y;o:“Signer 1”;w:100;h:15;}}`
For more details see the [Text Tag documentation](https://docs.signnow.com/text-tags#simple-text-tags)

**Comment by dMiracleMan** [comment]
thanks
