### ISSUE TITLE
Invalid token when creating a RoleBaseInvite

### ISSUE THREAD

**Issue by dMiracleMan** [signnow/SignNow.NET#95]
I'm using same token for all my calls.  The upload works, but when sending the invite, I get invalid_token error.

 var connToken = DigitalSignatureHelper.RequestAccessToken();
            var uploadedDocument =  DigitalSignatureHelper.UploadDocumentAsync(doc, co.approved_contract.Replace(" ", ""),connToken);
            var inviteResponse = DigitalSignatureHelper.CreateRoleBasedInviteToSignTheDocument(
                uploadedDocument,
                emails,
                connToken
                );

**Comment by AlexNDRmac** [comment]
Better - if you will use SignNowContext class. Because, it contains all services.
Also, you should care about token lifetime. You can check token expires_in param and if it expired - refresh with SignNow OAuth2 Service.

OAuth2 service has RefreshTokenAsync and ValidateTokenAsync methods, you can use any of these methods.

**Comment by dMiracleMan** [comment]
I believe that I'm using that class.

Here is the line causing the error:

return signNowContext.Invites.CreateInviteAsync(document.Id, invite).Result;

**Comment by AlexNDRmac** [comment]
Can you provide more details about exception? Also, please check if Token valid, before making invite request.

**Comment by dMiracleMan** [comment]
How do I check if is valid with the sdk? How to I refresh it? 
Here is the token information:
![image](https://user-images.githubusercontent.com/2863183/79483147-de2ac180-7fdf-11ea-82e8-c80668628de8.png)


 Error information:
![image](https://user-images.githubusercontent.com/2863183/79483258-0c100600-7fe0-11ea-8c39-a8166b716669.png)

**Comment by dMiracleMan** [comment]
I don't know if this has something to do, but the invite has two roles inside it.

Here is the code I'm trying:

            //Invite
            var invite = new RoleBasedInvite(document)
            {
                Message = $"CUSTOMiza invited you to sign the document {document.Name}",
                Subject = "The subject of the Email",
            };
           
            // Creates options for signers
            foreach (Role signer in signers.OrderBy(x=>x.SigningOrder))
            {
                var signerOptions = new SignerOptions(signer.Id, signer)
                {
                    ExpirationDays = 15,
                    RemindAfterDays = 7,

                };
                // Attach signer to existing roles in the document
                invite.AddRoleBasedInvite(signerOptions);
            }

            // Creating Invite request
            try
            {
                return signNowContext.Invites.CreateInviteAsync(document.Id, invite).Result;
            }
            catch (Exception ex)
            {
                return null;
            }`

**Comment by dMiracleMan** [comment]
Also, in the mean time, while debugging, before the call, I opened postman, the results shows that the token is valid.

![image](https://user-images.githubusercontent.com/2863183/79487321-17fec680-7fe6-11ea-88ba-080bcdac722c.png)

**Comment by AlexNDRmac** [comment]
You cant create your custom Role, only use roles existing in the document.
This code line is wrong: `foreach (Role signer in signers.OrderBy(x=>x.SigningOrder))`
And this code line also has mistake `var signerOptions = new SignerOptions(signer.Id, signer)`

How it looks in sources:
```csharp
/// <summary>
/// Initializes a new instance of the <see cref="SignerOptions"/> class.
/// </summary>
/// <param name="email"><see cref="Email"/> address of the signer.</param>
/// <param name="role"><see cref="Role"/> of the signer which will be required to fulfill.</param>
/// <exception cref="System.ArgumentNullException">if <see cref="Role"/> is null.</exception>
/// <exception cref="System.ArgumentException">if email is not valid.</exception>
public SignerOptions(string email, Role role)
{ ... }
```
Role in SignerOptions ctor args - must be exactly same as in document, for this purpose we have an accessor in RoleBasedInvite object, pls use it.

All you need is just get roles from document model.
```csharp
// Create new instance of RoleBased invite with document model as ctor param
var invite = new RoleBasedInvite(document);
// Retrieve existing document Roles
var roles = invite.DocumentRoles();
```
Than you can map your user `emails` with these `roles`

And small example with token refresh and validate:
```csharp
var oauth = new OAuth2Service(ApiBaseUrl, ClientInfo.Login, ClientInfo.Password);
var token = oauth.GetTokenAsync(UserCredentials.Login, UserCredentials.Password, Scope.All).Result;

Assert.IsNotNull(token.AccessToken);

// Refresh current Token
var newToken = oauth.RefreshTokenAsync(token).Result;
Assert.AreNotEqual(token, newToken);

// Validate Token
Assert.IsTrue(oauth.ValidateTokenAsync(newToken).Result);

// Creates SigNowContext
var signNowContext = new SignNowContext(ApiBaseUrl, newToken);
...
```

**Comment by dMiracleMan** [comment]
I'm closer but no luck yet.  

Changed it a little bit (some things are hard coded for testing)


 //using token from the Authorization step
            var signNowContext = new SignNowContext(SignNowToken);
            // Create role-based invite
            var invite = new RoleBasedInvite(document)
            {
                Message = $"CUSTOMiza invited you to sign the document {document.Name}",
                Subject = "The subject of the Email",
            };
            // Retrieve existing document Roles
            var roles = invite.DocumentRoles();
            int num = 1;
            foreach (Role role in roles)
            {
                var signerOptions = new SignerOptions(emails[num-1], role)
                {
                    ExpirationDays = 15,
                    RemindAfterDays = 7,
                    
                };
                // Attach signer to existing roles in the document
                invite.AddRoleBasedInvite(signerOptions);
                num++;
            }
           
            // Creating Invite request
            try
            {
                return signNowContext.Invites.CreateInviteAsync(document.Id, invite).Result;
            }
            catch (Exception ex)
            {
                return null;
            }

**Comment by AlexNDRmac** [comment]
Just copy and paste to your Tests... and replace credentials with your own...
I'm using MSTest framework in this example, if you don't - just replace Assertions
```csharp
[TestMethod]
public void Issue95()
{
    var oauth = new OAuth2Service(ApiBaseUrl, ClientInfo.Login, ClientInfo.Password);
    var token = oauth.GetTokenAsync(UserCredentials.Login, UserCredentials.Password, Scope.All).Result;

    Assert.IsNotNull(token.AccessToken);

    // Refresh current Token
    var newToken = oauth.RefreshTokenAsync(token).Result;
    Assert.AreNotEqual(token, newToken);

    // Validate Token
    Assert.IsTrue(oauth.ValidateTokenAsync(newToken).Result);

    // Creates SigNowContext
    var signNowContext = new SignNowContext(ApiBaseUrl, newToken);

    // Upload document with Field extract
    using var streamContent = new FileStream(PdfWithSignatureField, FileMode.Open);
    var initialDocument = signNowContext.Documents
        .UploadDocumentWithFieldExtractAsync(streamContent, "Issue95.pdf").Result;

    // Get SignNow document object by documentId
    var document = signNowContext.Documents.GetDocumentAsync(initialDocument.Id).Result;
    Assert.AreEqual(document.Id, initialDocument.Id);
    // Check document status - should be without invite
    Assert.AreEqual(DocumentStatus.NoInvite, document.Status);

    //Invite
    var invite = new RoleBasedInvite(document)
    {
        Message = $"CUSTOMiza invited you to sign the document {document.Name}",
        Subject = "The subject of the Email",
    };

    var signers = new Dictionary<String, String>()
    {
        {"Signer 1", "signer1@email.com" },
        {"Signer 2", "signer2@email.com" },
    };

    // Creates options for signers
    foreach (Role role in invite.DocumentRoles())
    {
        var userEmail = signers
                .First(x => x.Key == role.Name)
                .Value;

        var signerOptions = new SignerOptions(userEmail, role)
        {
            ExpirationDays = 15,
            RemindAfterDays = 7,

        };
        // Attach signer to existing roles in the document
        invite.AddRoleBasedInvite(signerOptions);
    }

    // Creating Invite request
    var inviteResponse = signNowContext.Invites.CreateInviteAsync(document.Id, invite).Result;

    // Check the document status
    var docStatus = signNowContext.Documents.GetDocumentAsync(document.Id).Result;
    Assert.AreEqual(DocumentStatus.Pending, docStatus.Status);
}
```
