### ISSUE TITLE
Error converting value "initials" to type 'SignNow.Net.Model.FieldType'

### ISSUE THREAD

**Issue by poctob** [signnow/SignNow.NET#96]
If a document contains initials field type, GetDocumentAsync method fails with the following exception:

Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in System.Private.CoreLib.dll: 'Error converting value "initials" to type 'SignNow.Net.Model.FieldType'. Path 'fields[10].type', line 1, position 19518.'

Field.cs line 75, enum is missing 'initials' type it has 'Initial' field instead

**Comment by AlexNDRmac** [comment]
Thank you for reporting. It will be fixed soon.

**Comment by poctob** [comment]
'Enumeration' fails as well. Changing 'Initial' to 'Initials' and 'Dropdown' to 'Enumeration' seems to fix the problem
